export const metadata = {
	title: "Auth | Monitoring IoT",
	description: "Generated by create next app",
	icons: {
		icon: [
			{ rel: "icon", url: "/favicon.ico" },
			{
				rel: "icon",
				url: "/logobrand.png",
				type: "image/png",
				sizes: "192x192",
			},
			{
				rel: "icon",
				url: "/logobrand.png",
				type: "image/png",
				sizes: "512x512",
			},
		],
		apple: [{ url: "/logobrand.png", sizes: "180x180", type: "image/png" }],
	},
};

export default function AuthLayout({ children }) {
	return <div>{children}</div>;
}
